# Documentation
# https://docs.docker.com/compose/compose-file

version: '3.2'

services:
  app_dev:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    env_file: 
      - ./.env
    volumes:
      - .:/app
    ports:
      - 7070:7070
